### ISSUE TITLE
Why not math/big.Rat?

### ISSUE THREAD

**Issue by jordancurve** [alex-ant/gomath#1]
Why does this package use its own rational.Rational instead of Rat from the built-in math.big package?

**Comment by jordancurve** [comment]
One problem is that rational.Rational gives the wrong answer when a numerator or denominator overflows an int64. big.Rat doesn't have this problem.

**Comment by alex-ant** [comment]
Agree, even though I've never thought of using such long numbers. Will switch to the built-in package instead.

**Comment by alex-ant** [comment]
The built-in Rat structure's methods are incredibly inconvenient in terms of performing multiple dependent calculations.

All the provided methods modify the original big.Rat structure by pointer and return the same pointer back which makes it tricky of making things like the following in one line:
(x + y) \* x

Here during the multiplication procedure the original X has already been modified by the previous action even though it'd be logical for the function just to return the result (as a new pointer or whatever).

I will be using rational.Rational type for my projects, although, it's a good point that there is an issue with the denominators longer for 64 bits.

**Comment by alex-ant** [comment]
Creating a new issue "rational.Rational gives the wrong answer when a numerator or denominator overflows an int64"
